
barcodes <- c("AAACGAACAATGGTAA","AAACGAAGTTTGCGAT","AAACGAATCCTGTGGG","AAACTGCCACAGTTAC","AAAGGGCTCCTTCGAC","AACCTTTGTGTCTCGG","AAGATAGTCCAGGTAT", "AATACGCAGTACAACA",
"AATACGCAGTTGCTTG","AATACGCGTGCTGTGC","AATACGCTCTCTGAGA","AATGCCAGTTTAAGGA","ACAAGCTGTAACATAG","ACAAGCTGTTTGCATG", "ACAATCGAGGACCGAT","ACAATCGGTAACTGAA",
"ACAGAAATCTTCCGTG","ACAGCGCGTGAGTAAT","ACAGCGCTCTTCATAC","ACAGGCCTCTTCCAGC","ACCAAACCAGAAAGAG","ACCCAAACACACACCG","ACCGAATTCGCAGATT","ACTACGATCATTCGGA",
"ACTATTCAGTGAAACT","ACTCGGGCAAATGCTC","ACTCGGGCACGCGATC","ACTGTCCCACCCATCT","ACTGTCCTCAGTACAC","ACTTCCGGTAAACGGC","ACTTCCGTCGGGCTCA","AGATAGACAAGTCCTA",
"AGCCAGCAGCAGGACT","AGCGATTAGTGAAACT","AGCTGTATCTATCCTA",
"AGGACGAGTCCGCTTT","AGGCCTGTCCAGGCCA","AGGCGTCTCTTCCAGC","AGTCCGGAGTTGAATG","AGTGTACTCTATCTCA","AGTTACGGTGTCTCGG","ATATTCCAGGACCGAT",
"ATCGAGTAGAGGTGGG","ATCGAGTCAATGTGCT","ATCGAGTTCCTGGGAC","ATGTCGAGTGCTGTGC","ATTGTCTCACTGATAC","ATTGTCTGTTCTCGAA","ATTGTCTTCCTTTGAT",
"ATTGTGGCAAGATTAG","ATTGTGGTCCTTGACC","ATTGTGGTCTCGGCGA","ATTTGTCCAATTGGCT","CAACCAAGTGTTGTTG","CAACGTACAAAGCTGG","CAAGCTACACCACAGC",
"CAAGGCCCAAAGCTGG","CAAGGCCCAAGTCCTA","CACATGAAGTAGACCG","CACATGACAATGTGCT","CACATGACAGCGTGAA","CACCACTGTGTCTCGG","CACCTTGCACAATAAG",
"CACTAAGTCGCTGATA","CAGCCTTCACTTGCGG","CAGCCTTTCGATATGC","CAGTATGTCGGCTATA","CATAACGAGTTCAGGG","CCAATGAGTGTGCTTA","CCACGTTCAATGGCTT",
"CCAGATAAGGTGATGC","CCCTAACCAGTCAGCC","CCCTCTCGTGCACTTA","CCGTACTGTACGCAAG","CCGTGAGGTATCTCAG","CCTAAAGAGGTGTTGG","CCTCCCTGTGTCTCGG",
"CCTTAATCATCTGCAA","CGCAATACAATACTGC","CGCACAGCAGCAGGTA","CGCACAGGTTAACTCG","CGCTGGAAGGGCTCTC","CGGACCAAGTGCACAG","CGGACTGGTGTTGTTG",
"CGTAAACCAAGATTAG","CGTAAACCACAGTTAC","CGTGGCATCTGATCCC","CTACTTAGTGAGTAAT","CTAGGATAGCAGTAGC","CTAGGATTCCAAGAGG","CTAGGGCCACCCATCT",
"CTCAGCTAGGCAAGGG","CTCAGCTTCACGTCAA","CTCAGCTTCTGACTTT","CTCGCTACAGCACATT","CTGAATGTCAGATACC","CTGCGTTCACTTATGG","CTGCGTTTCATCATGG",
"CTGCTCAAGTACGCGA","CTGCTCAGTGCGTTTA","CTGGCAGGTATCATGC","CTTCTAACAACGTCCG","CTTGAAGAGGTTAGTA","CTTGCCACACACACCG","CTTTGCGCACTTGCGG",
"GAAAGTACATAGACGG","GAACCTAAGTCGTACT","GAAGTGGGTATTCTCT","GAAGTGGTCCCTATTA","GAATCTGTCGCTAGTA","GACCAATGTGTCGGTC","GAGCGCTAGCTGATTC",
"GATCGTAAGGGTAGTC","GATGATCGTATTCGCA","GATGGCCGTTTCCGGG","GCACCTTAGATAGGTT","GCACCTTGTGCTGAAG","GCACCTTTCCTTCGAC","GCACGCACATCCCAAA",
"GCAGATTGTTCTGATG","GCAGCTGGTTCTTTGT","GCAGCTGTCAACTTGG","GCCAGACGTCCGCTTT","GCGAGTCCAGTTGCAT","GCGATCGAGTCTGTGT","GCGGAAAGTTTCGATG",
"GCGTTGGGTGCGACCT","GCTCCTACAAGATTAG","GCTGCGATCCCAATGA","GCTGCGATCTCGTAGA","GGAACTTAGGGTAATT","GGAACTTCAAGGAACC","GGAACTTTCCACGCTT",
"GGAACTTTCGCTGATA","GGAACTTTCGGCTATA","GGAACTTTCGGTTGTA","GGAATCTTCTTCCAGC","GGTACCGCAGTCAGCC","GGTAGGACATGGGTGA","GGTGAAGAGAGGAACA",
"GGTGAAGGTTTGCCAA","GGTGTCGAGTCAACTC","GGTGTCGTCGATAGGG","GGTTGCGAGAGTTCGG","GTACTTTGTTGGCTAT","GTCACTCCAGATACAA","GTGCCAGAGTACCTCA",
"GTGCCAGCAGACTAAA","GTGCTGGCAATTGTGC","GTGTGATTCCTGTGGG","GTTCAAGCATTAAGGA","TAACGGTAGTTTGGAA","TAACTTCGTCTGGGCT","TACAGCAGTCATTGCA",
"TACGCCTCAAACTACC","TACGGATCATGATCGT","TACGGATGTAAACGGC","TACTAGGCAGAGTCGA","TACTAGGGTTAGGCTT","TACTCGCTCCTTTGAT","TAGACTGAGTGATTAG",
"TAGACTGGTTTGCATG","TAGACTGTCCTCTCTT","TAGCCGGGTCCGCTTT","TAGTCCCTCTTCATAC","TATCGAGCAAGATTAG","TATCTGTAGCAATGTA","TATGTGGCAGGACTGA",
"TATGTGGGTGTCTCGG","TCAGCTCCAAGATTAG","TCAGGGCTCCAGAGAG","TCCAGAATCTCGTAGA","TCCCACAAGGGTAATT","TCCGACTGTATCACAC","TCGCCTATCCAGGTAT",
"TCTAGTTCAGTGCGAA","TCTATTGGTGTGACCC","TCTCTGGTCGACTGGC","TGACAACGTGCATCAT","TGATTTCTCAATCGTG","TGCCTGTGTTTGCATG","TGCCTGTGTTTGTGAC",
"TGCCTGTTCTTGTCGC","TGCTCGTAGTACAGAT","TGCTTTACATTGTGAC","TGGAAGGAGTCGACCC","TGGCGCAAGTGAAACT","TGGCGCACAAGTCCTA","TGGCGCACATAGATAG",
"TGGCGCAGTAGCGAGT","TGGTCAAGTGCTGTCG","TGTACAGAGGTTCGAG","TGTACAGGTTCTTTGT","TTAGCTTGTCCGTAGC","TTCAACTTCTCCTTAA","TTCATCAAGCATGATA",
"TTCATTGGTTAACTCG","TTCATTGTCCGATTGA","TTCGATTAGTTAGCAA","TTCGATTTCTCTATTG","TTCGGTCAGTCGTACT","TTGACGACAATTCTCT","TTGAGTGGTGGTAGAC",
"TTGCCCATCCAGGCCA","TTGCGAATCTTCATAC","TTGCGGGAGGCTGGAT","TTGCGGGAGTAGAAGG","TTGCGGGTCCCACTTG","TTGCGGGTCGGATAAA","TTGGTCCTCGTGGTAT",
"TTGTCTATCCATAACG","TTGTTGTTCCAATAGC","TTTACGTTCCTGACCT","TTTACGTTCGCCACTT","TTTGAGGAGTGGACGT","TTTGAGGCAGCGTCGT","TTTGAGGGTGCTGTGC",
"TTTGAGGTCAAGTTGC","TTTGCGCTCTCTTCTC")
barcodes.file.path <- "/sc/arion/projects/MDS/noelle/gotcha_pipeline_nwheeler/Gotcha_test_pipeline/GoTChA_test_data2/singlecell.csv"
whitelist <- load_whitelist(barcodes.file.path)


#
