---
title: "Genotype Labeling"
output: html_document
date: "2025-01-16"
---

load tet2
```{r}
out_collapsed_tet2 <- readRDS("/sc/arion/projects/MDS/NK_proj_simona_colla/NK_genotyping/BMGOT1-GOTCHA/fastqs/TET2/Split/Filtered/MergedOuts/outs.collapsed.Rdata")
out_collapsed_tet2$Sample <- "FRIZ01"

out_collapsed_srsf2 <- readRDS("/sc/arion/projects/MDS/NK_proj_simona_colla/NK_genotyping/BMGOT1-GOTCHA/fastqs/SRSF2/Split/Filtered/MergedOuts/outs.collapsed.Rdata")
out_collapsed_srsf2$Sample <- "FRIZ01"
```

filter out barcodes
```{r}
FRIZ01_CD56C_filt <- LoadH5Seurat("/sc/arion/projects/MDS/noelle/colla_NK_gotcha/FRIZ01_CD56C_filt.h5Seurat")
signac_cells <- Cells(FRIZ01_CD56C_filt)
signac_cells <- gsub("56C_", "", signac_cells)
signac_cells <- gsub("-1", "", signac_cells)

out_collapsed_tet2_filt  <- out_collapsed_tet2[which(out_collapsed_tet2$matched_barcodes %in% signac_cells),]
out_collapsed_srsf2_filt  <- out_collapsed_srsf2[which(out_collapsed_srsf2$matched_barcodes %in% signac_cells),]
```

column names
```{r}
colnames(out_collapsed_tet2_filt) <- c("WhiteListMatch", "WTcount", "MUTcount", "MUTfraction", "Sample")
colnames(out_collapsed_srsf2_filt) <- c("WhiteListMatch", "WTcount", "MUTcount", "MUTfraction", "Sample")
```


write csv
```{r}
write.csv(out_collapsed_tet2_filt, "/sc/arion/projects/MDS/noelle/colla_NK_gotcha/out_collapsed_tet2_filt.csv")
write.csv(out_collapsed_srsf2_filt, "/sc/arion/projects/MDS/noelle/colla_NK_gotcha/out_collapsed_srsf2_filt.csv")
```

run genotyping - need gotcha library installed (I ran on local computer)
will output in given path (not genotypes_TET2/SRSF2 objects!)
```{r}
genotypes_TET2 <- GotchaLabeling(path = "/sc/arion/projects/MDS/noelle/colla_NK_gotcha/", infile = "out_collapsed_tet2_filt.csv", gene_id = "TET2", sample_id = "FRIZ01_TET2")
genotypes_SRSF2 <- GotchaLabeling(path = "/sc/arion/projects/MDS/noelle/colla_NK_gotcha/", infile = "out_collapsed_srsf2_filt.csv", gene_id = "SRSF2", sample_id = "FRIZ01_SRSF")
```

